### ISSUE TITLE
Enhancement: Increase the height of Artist animated banners on a Artist page

### ISSUE THREAD

**Issue by KillerParticles** [yazninja/iTheme#16]
Currently, artist artwork in the artist page has a much smaller hight than that of the web page or Mac AM, this results in most of the video being cut off and strange to look at. What should happen is the video artwork should be increased in height in order to display more of the video and have it more natural looking. Below is what it looks like on the web which is a good size and you can see mostly all of the artists face, and below that is what your theme has, which only shows around half or under half of her face, which is not good to look at.

![image](https://user-images.githubusercontent.com/93286201/160120152-183060b3-bfbb-4c6b-9f3f-60bc2d9562c8.png)
![image](https://user-images.githubusercontent.com/93286201/160120228-068ec96d-2c33-45ac-9de7-2cb86aecb02d.png)

**Comment by yazninja** [comment]
I tried to do it, the navigation bars really become an obstruction tho, its more obvious

**Comment by vapormusic** [comment]
Why
This is small for a reason smh
