### ISSUE TITLE
Cannot read Artist name in song/Album view in Light mode

### ISSUE THREAD

**Issue by KillerParticles** [yazninja/iTheme#8]
![image](https://user-images.githubusercontent.com/93286201/159492149-79e572c8-3817-463e-a2e0-f722ace1ee20.png)

The Artist name is in white when in light mode, white on white making it almost impossible to read it.

**Comment by yazninja** [comment]
LOL, I keep missing stuff in light mode

**Comment by KillerParticles** [comment]
I don't blame ya lol Cider was made for dark mode so converting it to Light modes gonna be tough :)
